import Config from 'react-native-config';

export default {
  API_URL: Config.REACT_NATIVE_API_URL,
  REACT_NATIVE_API_KEY: Config.REACT_NATIVE_API_KEY,
  GOOGLE_API_KEY: Config.GOOGLE_API_KEY,
  GOOGLE_MAPS_API_KEY: Config.GOOGLE_MAPS_API_KEY,
  FIREBASE_API_KEY: Config.FIREBASE_API_KEY,
  SENTRY_DSN: Config.SENTRY_DSN,
  STRIPE_PUBLISHABLE_KEY: Config.STRIPE_PUBLISHABLE_KEY,
  S3_BUCKET: Config.S3_BUCKET,
  S3_REGION: Config.S3_REGION,
  NODE_ENV: Config.NODE_ENV,
};
